version: '3.7'

services:

  mongo:
    image: neo4j
    restart: always
    ports:
      - 7474:7474 
      - 7687:7687
    environment:
      MONGO_INITDB_ROOT_USERNAME: neo4j
      MONGO_INITDB_ROOT_PASSWORD: test
    volumes:
      - $PWD/neo4j/data:/data
      - $PWD/neo4j/logs:/logs
      - $PWD/neo4j/import:/var/lib/neo4j/import
      - $PWD/neo4j/plugins:/plugins